server:
    port: 0
    connection-timeout: 5000ms
    http2:
      enabled: true

debug: false

logging:
  level:
    root: info

spring:
  application:
    name: ideal-consumer
  profiles:
    active: dev
  transaction:
    rollback-on-commit-failure: true
  mvc:
    throw-exception-if-no-handler-found: true
    servlet:
      load-on-startup: 1
  aop:
    auto: true
    proxy-target-class: true
  http:
    encoding:
      enabled: true
      force: true
      charset: utf-8
    converters:
      preferred-json-mapper: jackson
#  resources:
#    add-mappings: false

--- # 开发环境**********************************************************************************************************
spring:
  profiles: dev

eureka:
  instance:
    health-check-url-path: /actuator/health
    lease-renewal-interval-in-seconds: 10
  client:
    serviceurl:
      defaultzone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always